Add nodejs demo
cndt-app/api_demo pull request #8
Opened 2022-09-21 21:10 UTC by denis-manakov-cndt

https://app.asana.com/0/home/1202734767782127/1203009409917105

2022-09-22 07:19 UTC, dmitrii-sorokin-cndt commented on demo1_nodejs/README.md
> +# A command line Conduit Link API demo client.
я ожидаю ровно 1 документ.
в котором может быть описано и подготовительная часть, если нужно.

разбивать на 2 документа не надо

2022-09-22 07:20 UTC, dmitrii-sorokin-cndt commented on demo1_nodejs/step_by_step.md
> +### Предварительный этап
у тебя есть папка Docs - значит туда и надо было положить

2022-09-22 07:32 UTC, dmitrii-sorokin-cndt commented on demo1_nodejs/step_by_step.md
> +(информация как получить токен есть в [README.md](./README.md) не дублирую)
получение токена - надо описать в начале документа
и тут "токен из пункта #X "

2022-09-22 07:34 UTC, dmitrii-sorokin-cndt commented on demo1_nodejs/step_by_step.md
> +Сначала необходимо импортировать библиотеку:
Для начала подготовим основу.
Импортируем библиотеку и создадим асинхронную функцию верхнего уровня

и тут кусок кода из 2х пунктов сразу,
нет смысла так сильно разбивать

2022-09-22 07:34 UTC, dmitrii-sorokin-cndt commented on demo1_nodejs/step_by_step.md
> +Обращение к эндпоинту `/link/credentials/` будет выглядеть следующим образом:
что это за endpoint?
зачем он нужен?

это должен быть гайд который расскрывает не только КАК но и ЗАЧЕМ

2022-09-22 07:35 UTC, dmitrii-sorokin-cndt commented on demo1_nodejs/step_by_step.md
> +let response = await axios.get(
мы до этого сделали запрос.
зачем? не понятно
просто переходим к другому запросу

делаем запросы ради запросов

2022-09-23 06:59 UTC, egor-rudinsky-cndt requested changes

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +async function request(endpoint, params = {}) {
почему тут async функция, если нет внутри ниодного await? потому что просто возвращает промис?

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +CONDUIT_CUSTOMER_API_KEY = ' place your api key here '
```suggestion
const CONDUIT_API_URL = 'https://api.getconduit.app'
const CONDUIT_CUSTOMER_API_KEY = ' place your api key here '
```

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +async function request(endpoint, params = {}) {
давай назовем функцию `httpGet` и сделаем ее выше остальных в файле

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +    let fullPath = new URL(endpoint, CONDUIT_API_URL).href
https://axios-http.com/docs/config_defaults

const instance = axios.create({
  baseURL: 'https://api.example.com'
});

baseURL ровно для этого и нужен, чтобы не делать не самый очевидный fullPath

\+ можно сразу же зашить headers.accept, но нужно?

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +module.exports = {getDataChunks, getCredentials}
новая строка + в js все таки принято делать `{ keyOne, keyTwo }`

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +async function getDataChunks(integration, date_from, date_to, account) {
параметры в camelCase надо

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/index.js
> +const fs = require("fs");
надо определиться какой styleguide ты используешь(airbnb или google), тк тут у тебя есть ; в конце, строки, где-то нет.

Так что предлагаю прогнать файл через eslint --fix с google пресетом.

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +    return axios.get(fullPath, {headers: headers, params: params})
пустая строка перед return

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/conduit_link.js
> +    return response.data
пустая строка перед return

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/index.js
> +        moment().subtract(6, 'days').format('YYYY-MM-DD'),
moment это больше фронтовая штука, date-fns куда легче к восприятию для бэкендеров должно быть

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/package.json
> +    "main": "node index.js"
main для js это start скрипт, заодно еще потом запуск через npm start.

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/README.md
> +    })
а токен тут нигде не понадобится?

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/README.md
> +})()
вот так никогда не надо делать.

давай лучше [top level await](https://blog.saeloun.com/2021/11/25/ecmascript-top-level-await.html#:~:text=Top%2Dlevel%20await%20enables%20modules,wait%20before%20evaluating%20their%20code.), и тогда файл надо назвать `.mjs`

те будет
```js
async main() {
}

await main();
```

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/README.md
> +    console.log(e)
```suggestion
    console.error(e)
```

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/index.js
> +                + `updated_at: ${chunk.data_updated_at}`
https://www.samanthaming.com/tidbits/58-multi-line-strings-with-template-literals/

либо просто сделать 
`console.table({ ...chunk, schema })`

2022-09-23 06:59 UTC, egor-rudinsky-cndt commented on demo1_nodejs/index.js
> +    let data_chunks = await getDataChunks(integration_id, date_from, date_to, account)
```suggestion
    let dataChunks = await getDataChunks(integration_id, date_from, date_to, account)
```

camelCase

2022-09-26 14:06 UTC, egor-rudinsky-cndt requested changes

2022-09-26 14:06 UTC, egor-rudinsky-cndt commented on demo1_nodejs/index.mjs
> +    await main(date_range)
```suggestion
    let dateRange = [
        moment().subtract(6, 'days').format('YYYY-MM-DD'),
        moment().format('YYYY-MM-DD'),
    ]
    await main(dateRange)
```

2022-09-26 14:07 UTC, egor-rudinsky-cndt commented on demo1_nodejs/package.json
> +    "main": "node index.js"
не исправлено

2022-09-27 08:01 UTC, egor-rudinsky-cndt requested changes

2022-09-27 08:16 UTC, egor-rudinsky-cndt approved these changes

2022-09-27 08:17 UTC, egor-rudinsky-cndt commented on demo1_nodejs/README.md
> +Run `npm run main`
```suggestion
Run `npm start`
```

2022-09-27 08:17 UTC, merged